development:
  clients:
    default:
      uri: mongodb+srv://test-user:chllngpsswrd@challenge-cluster.spicyha.mongodb.net/?retryWrites=true&w=majority&appName=challenge-cluster
      options:
        server_selection_timeout: 5