development:
  clients:
    default:
      uri: mongodb+srv://challenge_username:<password>@challenge-cluster.spicyha.mongodb.net/?retryWrites=true&w=majority&appName=challenge-cluster
      options:
        server_selection_timeout: 1